// All products data - matches schema.ts structure
export const allProducts = [
  {
    id: 1,
    name: "Modern Full Stack Next.js Course",
    slug: "modern-full-stack-nextjs-course",
    tagline: "Learn to build modern full stack applications with Next.js",
    description:
      "Learn to build modern full stack applications with Next.js 16.",
    websiteUrl: "https://nextjscourse.dev",
    tags: ["Next.js", "Tailwind CSS", "Full Stack"],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
    approvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "john@example.com",
    voteCount: 120,
  },
  {
    id: 2,
    name: "TaskFlow Pro",
    slug: "taskflow-pro",
    tagline: "Manage projects like never before",
    description:
      "Streamline your team's workflow with intelligent task management, automated notifications, and real-time collaboration features.",
    websiteUrl: "https://taskflowpro.example.com",
    tags: ["Productivity", "SaaS"],
    createdAt: new Date("2024-01-18"),
    approvedAt: new Date("2024-01-19"),
    status: "approved" as const,
    submittedBy: "mike@example.com",
    voteCount: 87,
  },
  {
   
    id: 3,
    name: "CodeSnap",
    slug: "codesnap",
    tagline: "Beautiful code screenshots for developers",
    description:
      "Create stunning code screenshots with customizable themes, syntax highlighting, and export options.",
    aiDescription: null,
    websiteUrl: "https://codesnap.example.com",
    tags: ["Developer Tools", "Design"],
    voteCount: 56,
    status: "approved",
    submittedBy: "alex@example.com",
    userId: null,
    organizationId: null,
    aiMetadata: null,
    createdAt: new Date("2024-01-20"),
    approvedAt: new Date("2024-01-21"),
  },
  {
    id: 4,
    name: "ProofyBubble",
    slug: "proofybubble",
    tagline: "Social proof notifications that convert visitors",
    description:
      "Boost your website conversions with real-time social proof notifications.",
    aiDescription: null,
    websiteUrl: "https://proofybubble.com",
    tags: ["Marketing", "SaaS", "Conversion"],
    voteCount: 523,
    status: "approved",
    submittedBy: "proofy@example.com",
    userId: null,
    organizationId: null,
    aiMetadata: null,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: 5,
    name: "ParityKit",
    slug: "paritykit",
    tagline: "Price parity for global SaaS products",
    description:
      "Maximize your global revenue with intelligent price localization.",
    aiDescription: null,
    websiteUrl: "https://paritykit.com",
    tags: ["SaaS", "Pricing", "Global"],
    voteCount: 612,
    status: "approved",
    submittedBy: "parity@example.com",
    userId: null,
    organizationId: null,
    aiMetadata: null,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    id: 9,
    name: "Developer to Leader Course",
    slug: "developer-to-leader-course",
    tagline: "Learn to lead a team of developers",
    description:
      "Learn to lead a team of developers and become a leader in your field.",
    aiDescription: null,
    websiteUrl: "https://developertoleader.com",
    tags: ["Leadership", "Management", "Development"],
    voteCount: 340,
    status: "pending",
    submittedBy: "kulkarni.ankita09@gmail.com",
    userId: null,
    organizationId: null,
    aiMetadata: null,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    approvedAt: null,
  },
 
];